[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "triplepy"
version = "1.0.1"
authors = [
  { name="Paul Hoffrogge", email="mail@paul-hoffrogge.de" },
  { name="Simon Daubner", email="simon.daubner@kit.edu" },
  { name="Bei Zhou", email="b.zhou@access-technology.de" }
]
description = "A benchmark for GB migration subject to capillary and bulk driving forces."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["numpy", "scipy", "scikit-image", "vtk", "pint", "mip"]

[project.optional-dependencies]
test = ["pytest", "ruff"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = ["tests"]
pythonpath = ["src"]

[tool.ruff]
target-version = "py39"

[project.urls]
Homepage = "https://github.com/Triple-Junction/triplepy"
Issues = "https://github.com/Triple-Junction/triplepy/issues"
